// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetService.proto

package com.example.grpc.protocol;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.protocol.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
