// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetService.proto

package com.example.grpc.protocol;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.protocol.GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
